{% set name = "mnelab" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3f10ca6cce950de8d7392f66ec6b5b5887be5df091f104d24076521789b9c13e

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - mnelab = mnelab.__main__:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - matplotlib >=2.0.0
    - mne >=0.17.1
    - numpy >=1.8.1
    - pyedflib
    - pyqt >=5.6.0
    - python-picard
    - pyxdf
    - scikit-learn
    - scipy >=0.17.1

test:
  imports:
    - mnelab
    - mnelab.utils

about:
  home: https://github.com/cbrnr/mnelab
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Graphical user interface (GUI) for MNE, a Python-based toolbox for EEG/MEG analysis.'

extra:
  recipe-maintainers:
    - hoechenberger
